name: Store Form Data

on:
  workflow_dispatch:
  repository_dispatch:
    types: [store_form_data]

jobs:
  store-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create data file if it does not exist
      run: |
        if [ ! -f "form_data.txt" ]; then
          echo "Name,Email,Message" > form_data.txt
        fi

    - name: Add form data to file
      run: |
        echo "${{ github.event.client_payload.name }},${{ github.event.client_payload.email }},${{ github.event.client_payload.message }}" >> form_data.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add form_data.txt
        git commit -m "Add form data"
        git push
